errbot:
  build: .
  environment:
    - WAIT=10
    - BACKEND=SlackV3
    - BOT_IDENTITY_TOKEN=xoxb-111111111111-1111111111111-11X1XX1X1XXXXXXXXXXXXXX1
    - BOT_SIGNING_SECRET=11X1XX1X11111XXX1X111111X1XX11XX
    - BOT_APP_TOKEN=xapp-1-X11XXX1X1XX-1111111111111-1XX1111XXX1111X11XXXX111XX1X1X1111X11XX1XX1XXX111XXX1111XXX11111
    - BOT_ADMINS=U11X111XXXX
    - BOT_ADMINS_NOTIFICATIONS=@U11X111XXXX
    - BOT_ALT_PREFIXES=errbot
    - BOT_LOG_LEVEL=WARNING
    - CHATROOM_PRESENCE=""
  dns: 172.17.0.1

dnsdock:
  image: tonistiigi/dnsdock
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - 172.17.0.1:53:53/udp
